config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [:new, :create]

  get '/:code', to: 'urls#redirect'

  root to: 'urls#new'

end

app/models/url.rb
require "#{ Rails.root }/lib/random_token_generator.rb"

class Url < ActiveRecord::Base
  include RandomTokenGenerator

  before_create :generate_code

  validates :target, presence: true
  validates :target, url: true, allow_blank: true

  private
    def generate_code
      code = token(10)

      unless Url.where(code: token).exists?
        code = token(10)
      end
      self.code = code
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :load_url, only: :redirect

  def new
    @url = Url.new
  end

  def create
    @url = Url.find_or_initialize_by(url_params)
    if @url.save
      render json: @url.to_json, status: 200
    else
      render json: { errors: @url.errors.full_messages }, status: 422
    end
  end

  def redirect
    redirect_to @url.target, status: 301
  end

  private
    def load_url
      @url = Url.where(code: params[:code]).first
      unless @url
        render nothing: true, status: 404
      end
    end

    def url_params
      params.require(:url).permit(:target)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :scripts %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url, remote: true, html: { id: 'urls-form' } do |f| %>
  <div class='flash'>
    
  </div>

  <div class="field">
    <%= f.label :target %><br>
    <%= f.text_area :target %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

<div id='urls-area'>
  
</div>

<%= link_to 'Back', urls_path %>

<%= render template: 'templates/urls_table', formats: :tmpl %>
<%= render template: 'templates/urls_row', formats: :tmpl %>
<%= render template: 'templates/flash_message', formats: :tmpl %>